POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImhvZ2UiLCJpZCI6IjVlYjI3OTNkNmE1ZmJmMGIyZjUxNjI3NCIsImlhdCI6MTU4ODc3OTEwMX0.Ju9BnOneB7f_JBl43PRcj7zkNYH5PfLOV6wJGP4Go7s

{
    "title": "dfasdfasdfas",
}